// <auto-generated />
using System;
using EcoSafe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoSafe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoSafe.Models.ABRIGO", b =>
                {
                    b.Property<int>("ID_ABRIGO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ABRIGO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ABRIGO"));

                    b.Property<int>("CAPACIDADE")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACIDADE");

                    b.Property<string>("ENDERECO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<int>("OCUPACAO_ATUAL")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OCUPACAO_ATUAL");

                    b.HasKey("ID_ABRIGO");

                    b.ToTable("ABRIGO");
                });

            modelBuilder.Entity("EcoSafe.Models.ALERTA", b =>
                {
                    b.Property<int>("ID_ALERTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ALERTA"));

                    b.Property<int>("ABRIGOID_ABRIGO")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("ID_ABRIGO")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ABRIGO");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.HasKey("ID_ALERTA");

                    b.HasIndex("ABRIGOID_ABRIGO");

                    b.ToTable("ALERTA");
                });

            modelBuilder.Entity("EcoSafe.Models.APPUSER", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("LOCALIZACAO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("APPUSER");
                });

            modelBuilder.Entity("EcoSafe.Models.LEITURA_SENSOR", b =>
                {
                    b.Property<int>("ID_LEITURA_SENSOR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_LEITURA_SENSOR"));

                    b.Property<DateTime>("DATA_LEITURA")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA");

                    b.Property<int>("ID_SENSOR")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<int>("SENSORID_SENSOR")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("VALOR")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("ID_LEITURA_SENSOR");

                    b.HasIndex("SENSORID_SENSOR");

                    b.ToTable("LEITURA_SENSOR");
                });

            modelBuilder.Entity("EcoSafe.Models.SENSOR", b =>
                {
                    b.Property<int>("ID_SENSOR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SENSOR"));

                    b.Property<int>("ABRIGOID_ABRIGO")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ID_ABRIGO")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ABRIGO");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.HasKey("ID_SENSOR");

                    b.HasIndex("ABRIGOID_ABRIGO");

                    b.ToTable("SENSOR");
                });

            modelBuilder.Entity("EcoSafe.Models.ALERTA", b =>
                {
                    b.HasOne("EcoSafe.Models.ABRIGO", "ABRIGO")
                        .WithMany("ALERTAS")
                        .HasForeignKey("ABRIGOID_ABRIGO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ABRIGO");
                });

            modelBuilder.Entity("EcoSafe.Models.LEITURA_SENSOR", b =>
                {
                    b.HasOne("EcoSafe.Models.SENSOR", "SENSOR")
                        .WithMany("LEITURAS")
                        .HasForeignKey("SENSORID_SENSOR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SENSOR");
                });

            modelBuilder.Entity("EcoSafe.Models.SENSOR", b =>
                {
                    b.HasOne("EcoSafe.Models.ABRIGO", "ABRIGO")
                        .WithMany("SENSORES")
                        .HasForeignKey("ABRIGOID_ABRIGO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ABRIGO");
                });

            modelBuilder.Entity("EcoSafe.Models.ABRIGO", b =>
                {
                    b.Navigation("ALERTAS");

                    b.Navigation("SENSORES");
                });

            modelBuilder.Entity("EcoSafe.Models.SENSOR", b =>
                {
                    b.Navigation("LEITURAS");
                });
#pragma warning restore 612, 618
        }
    }
}
